
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintApplication;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Saad
 */
public class LineWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form LineWindow
     */
    private Color borderColor0 = Color.black;
    private Node parent;
    private LineSegment line;
    private Canvas canvas;
    private JComboBox<String> jComboBox;
    private Engine engine;
    private int numberOfLines;
    
    public LineWindow(Canvas canvas, JComboBox<String> jComboBox, Engine engine) {
        initComponents();
        line = null;
        this.canvas = canvas;
        this.jComboBox = jComboBox;
        this.engine = engine; 
    }
    
    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    
    @Override
    public Node getParentNode() {
        return this.parent;
    }
    
    public boolean isNumeric(String str) {
        for(int i=0; i<str.length(); i++) {
            if (!(str.charAt(i) >='0' && str.charAt(i)<='9')) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        y2 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        ix1 = new javax.swing.JTextField();
        ix2 = new javax.swing.JTextField();
        iy2 = new javax.swing.JTextField();
        iy1 = new javax.swing.JTextField();
        borderColor = new javax.swing.JButton();
        drawLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Draw Line");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x1.setBackground(new java.awt.Color(255, 153, 0));
        x1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x1.setForeground(new java.awt.Color(0, 0, 0));
        x1.setText("X1 Coordinate");
        x1.setOpaque(true);
        getContentPane().add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 21, 156, 40));

        x2.setBackground(new java.awt.Color(255, 153, 0));
        x2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x2.setForeground(new java.awt.Color(0, 0, 0));
        x2.setText("X2 Coordinate");
        x2.setOpaque(true);
        getContentPane().add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 138, 156, 40));

        y2.setBackground(new java.awt.Color(255, 153, 0));
        y2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y2.setForeground(new java.awt.Color(0, 0, 0));
        y2.setText("y2 Coordinate");
        y2.setOpaque(true);
        getContentPane().add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 197, 156, 40));

        y1.setBackground(new java.awt.Color(255, 153, 0));
        y1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y1.setForeground(new java.awt.Color(0, 0, 0));
        y1.setText("y1 Coordinate");
        y1.setOpaque(true);
        getContentPane().add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 79, 156, 40));

        ix1.setBackground(new java.awt.Color(0, 0, 0));
        ix1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix1.setForeground(new java.awt.Color(255, 153, 0));
        ix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ix1ActionPerformed(evt);
            }
        });
        getContentPane().add(ix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 21, 157, 40));

        ix2.setBackground(new java.awt.Color(0, 0, 0));
        ix2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix2.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(ix2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 139, 157, 40));

        iy2.setBackground(new java.awt.Color(0, 0, 0));
        iy2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy2.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(iy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 198, 157, 40));

        iy1.setBackground(new java.awt.Color(0, 0, 0));
        iy1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy1.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(iy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 80, 157, 40));

        borderColor.setBackground(new java.awt.Color(0, 0, 0));
        borderColor.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        borderColor.setForeground(new java.awt.Color(255, 153, 0));
        borderColor.setText("Border Color");
        borderColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorActionPerformed(evt);
            }
        });
        getContentPane().add(borderColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 256, 190, 40));

        drawLine.setBackground(new java.awt.Color(0, 0, 0));
        drawLine.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        drawLine.setForeground(new java.awt.Color(255, 153, 0));
        drawLine.setText("Draw Line");
        drawLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawLineActionPerformed(evt);
            }
        });
        getContentPane().add(drawLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 308, 331, 75));

        setSize(new java.awt.Dimension(378, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ix1ActionPerformed

    private void drawLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawLineActionPerformed
        // TODO add your handling code here:
        
        String strx1 = ix1.getText();
        String stry1 = iy1.getText();
        String strx2 = ix2.getText();
        String stry2 = iy2.getText();
        
        if (strx1.equals("") || stry1.equals("") || strx2.equals("") || stry2.equals("")) {
            JOptionPane.showMessageDialog(null, "Some Fields are Empty !");
        }
        
        else if (!isNumeric(strx1) || !isNumeric(stry1) || !isNumeric(strx2) || !isNumeric(stry2) ) {
            JOptionPane.showMessageDialog(null, "Only Positive Numeric Values Are Allowed, Please Try Again!");
            if (!isNumeric(strx1)) {ix1.setText("");}
            if (!isNumeric(strx2)) {ix2.setText("");}
            if (!isNumeric(stry1)) {iy1.setText("");}
            if (!isNumeric(stry2)) {iy2.setText("");}
        }
        
        else {
            
            int x1 = Integer.parseInt(strx1);
            int x2 = Integer.parseInt(strx2);
            int y1 = Integer.parseInt(stry1);
            int y2 = Integer.parseInt(stry2);
            
            line = new LineSegment(new Point(x1,y1), new Point(x2,y2));     
            line.setColor(borderColor0);
            this.engine.addShape(line);
            this.line.draw(canvas.getGraphics());
            borderColor0 = Color.BLACK;
            String lineName = "line" + this.numberOfLines;
            this.jComboBox.addItem(lineName);
            this.numberOfLines++;
            this.engine.refresh(canvas.getGraphics()); 
            this.setVisible(false);
//             Paint paint = (Paint) this.getParentNode();
//             paint.setVisible(true);
            ix1.setText("");
            ix2.setText("");
            iy1.setText("");
            iy2.setText("");
        }
        
    }//GEN-LAST:event_drawLineActionPerformed

    private void borderColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Enter Color :", Color.yellow);
        if(color != null) {
            this.borderColor0 = color;
        }
    }//GEN-LAST:event_borderColorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//        try {
//            UIManager.setLookAndFeel(new FlatDarkLaf());
//        }
//        catch (Exception e) {
//            e.printStackTrace();
//        }
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(LineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(LineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(LineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(LineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LineWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColor;
    private javax.swing.JButton drawLine;
    private javax.swing.JTextField ix1;
    private javax.swing.JTextField ix2;
    private javax.swing.JTextField iy1;
    private javax.swing.JTextField iy2;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    // End of variables declaration//GEN-END:variables
}
