/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintApplication;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Saad
 */
public class RectangleWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form RectangleWindow
     */
    private Node parent;
    private Rectangle rectangle;
    private Color borderColor0 = Color.black;
    private Color fillColor0 = null;
    private Canvas canvas;
    private JComboBox<String> jComboBox;
    private Engine engine;
    private int numberOfRectangles;
    
    public RectangleWindow(Canvas canvas, JComboBox<String> jComboBox, Engine engine) {
        initComponents();
        rectangle = null;
        this.canvas = canvas;
        this.jComboBox = jComboBox;
        this.engine = engine; 
    }
    
    public boolean isNumeric(String str) {
        for(int i=0; i<str.length(); i++) {
            if (!(str.charAt(i) >='0' && str.charAt(i)<='9')) {
                return false;
            }
        }
        return true;
    }
    
    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    
    @Override
    public Node getParentNode() {
        return this.parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x1 = new javax.swing.JLabel();
        width = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        ix1 = new javax.swing.JTextField();
        iwidth = new javax.swing.JTextField();
        iheight = new javax.swing.JTextField();
        iy1 = new javax.swing.JTextField();
        fill = new javax.swing.JButton();
        drawRect = new javax.swing.JButton();
        borderColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Draw Rectangle");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x1.setBackground(new java.awt.Color(255, 153, 0));
        x1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x1.setForeground(new java.awt.Color(0, 0, 0));
        x1.setText("X1 Coordinate");
        x1.setOpaque(true);
        getContentPane().add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 25, 156, 40));

        width.setBackground(new java.awt.Color(255, 153, 0));
        width.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        width.setForeground(new java.awt.Color(0, 0, 0));
        width.setText("          Width");
        width.setOpaque(true);
        getContentPane().add(width, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 142, 156, 40));

        height.setBackground(new java.awt.Color(255, 153, 0));
        height.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        height.setForeground(new java.awt.Color(0, 0, 0));
        height.setText("         Height");
        height.setOpaque(true);
        getContentPane().add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 201, 156, 40));

        y1.setBackground(new java.awt.Color(255, 153, 0));
        y1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y1.setForeground(new java.awt.Color(0, 0, 0));
        y1.setText("y1 Coordinate");
        y1.setOpaque(true);
        getContentPane().add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 83, 156, 40));

        ix1.setBackground(new java.awt.Color(0, 0, 0));
        ix1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix1.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(ix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 25, 157, 40));

        iwidth.setBackground(new java.awt.Color(0, 0, 0));
        iwidth.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iwidth.setForeground(new java.awt.Color(255, 153, 0));
        iwidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iwidthActionPerformed(evt);
            }
        });
        getContentPane().add(iwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 143, 157, 40));

        iheight.setBackground(new java.awt.Color(0, 0, 0));
        iheight.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iheight.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(iheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 202, 157, 40));

        iy1.setBackground(new java.awt.Color(0, 0, 0));
        iy1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy1.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(iy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 84, 157, 40));

        fill.setBackground(new java.awt.Color(0, 0, 0));
        fill.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        fill.setForeground(new java.awt.Color(255, 153, 0));
        fill.setText("Fill Color");
        fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillActionPerformed(evt);
            }
        });
        getContentPane().add(fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 272, 190, 40));

        drawRect.setBackground(new java.awt.Color(0, 0, 0));
        drawRect.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        drawRect.setForeground(new java.awt.Color(255, 153, 0));
        drawRect.setText("Draw Rectangle");
        drawRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRectActionPerformed(evt);
            }
        });
        getContentPane().add(drawRect, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 330, 331, 75));

        borderColor.setBackground(new java.awt.Color(0, 0, 0));
        borderColor.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        borderColor.setForeground(new java.awt.Color(255, 153, 0));
        borderColor.setText("Border Color");
        borderColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorActionPerformed(evt);
            }
        });
        getContentPane().add(borderColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 272, 190, 40));

        setSize(new java.awt.Dimension(414, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iwidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iwidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iwidthActionPerformed

    private void fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Enter Color :", Color.yellow);
        if(color != null) {
            this.fillColor0 = color;
        }
    }//GEN-LAST:event_fillActionPerformed

    private void borderColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Enter Color :", Color.yellow);
        if(color != null) {
            this.borderColor0 = color;
        }
    }//GEN-LAST:event_borderColorActionPerformed

    private void drawRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRectActionPerformed
        // TODO add your handling code here:
        String strx1 = ix1.getText();
        String stry1 = iy1.getText();
        String strwidth = iwidth.getText();
        String strheight = iheight.getText();
        
        if (strx1.equals("") || stry1.equals("") || strwidth.equals("") || strheight.equals("")) {
            JOptionPane.showMessageDialog(null, "Some Fields are Empty !");
        }
        
        else if (!isNumeric(strx1) || !isNumeric(stry1) || !isNumeric(strwidth) || !isNumeric(strheight) ) {
            JOptionPane.showMessageDialog(null, "Only Positive Numeric Values Are Allowed, Please Try Again!");
            if (!isNumeric(strx1)) {ix1.setText("");}
            if (!isNumeric(stry1)) {iy1.setText("");}
            if (!isNumeric(strwidth)) {iwidth.setText("");}
            if (!isNumeric(strheight)) {iheight.setText("");}
        }
        
        else {
            
            int x1 = Integer.parseInt(strx1);
            int y1 = Integer.parseInt(stry1);
            int width = Integer.parseInt(strwidth);
            int height = Integer.parseInt(strheight);
            
            rectangle = new Rectangle(new Point(x1,y1), width, height);     
            rectangle.setColor(borderColor0);
            rectangle.setFillColor(fillColor0);
            this.engine.addShape(rectangle);
            this.rectangle.draw(canvas.getGraphics());
            borderColor0 = Color.BLACK;
            fillColor0 = null;
            String rectangleName = "rectangle" + this.numberOfRectangles;
            this.jComboBox.addItem(rectangleName);
            this.numberOfRectangles++;
            this.engine.refresh(canvas.getGraphics()); 
            this.setVisible(false);
//             Paint paint = (Paint) this.getParentNode();
//             paint.setVisible(true);
            ix1.setText("");
            iheight.setText("");
            iy1.setText("");
            iwidth.setText("");
    }//GEN-LAST:event_drawRectActionPerformed
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RectangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RectangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RectangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RectangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RectangleWindow().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColor;
    private javax.swing.JButton drawRect;
    private javax.swing.JButton fill;
    private javax.swing.JLabel height;
    private javax.swing.JTextField iheight;
    private javax.swing.JTextField iwidth;
    private javax.swing.JTextField ix1;
    private javax.swing.JTextField iy1;
    private javax.swing.JLabel width;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel y1;
    // End of variables declaration//GEN-END:variables
}

