/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintApplication;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.lang.Math.*;

/**
 *
 * @author Saad
 */
public class TriangleWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form TriangleWindow
     */
    private Node parent;
    private Triangle triangle;
    private Color borderColor0 = Color.black;
    private Color fillColor0 = null;
    private Canvas canvas;
    private JComboBox<String> jComboBox;
    private Engine engine;
    private int numberOfTriangles;
    
    public TriangleWindow(Canvas canvas, JComboBox<String> jComboBox, Engine engine) {
        initComponents();
        triangle = null;
        this.canvas = canvas;
        this.jComboBox = jComboBox;
        this.engine = engine;
    }
    
    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    
    @Override
    public Node getParentNode() {
        return this.parent;
    }
    
    public boolean isNumeric(String str) {
        for(int i=0; i<str.length(); i++) {
            if (!(str.charAt(i) >='0' && str.charAt(i)<='9')) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x1 = new javax.swing.JLabel();
        y2 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        ix1 = new javax.swing.JTextField();
        iy3 = new javax.swing.JTextField();
        iy1 = new javax.swing.JTextField();
        drawTri = new javax.swing.JButton();
        y3 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        ix3 = new javax.swing.JTextField();
        iy2 = new javax.swing.JTextField();
        ix2 = new javax.swing.JTextField();
        borderColor = new javax.swing.JButton();
        fillColor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Draw Triangle");

        x1.setBackground(new java.awt.Color(255, 153, 0));
        x1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x1.setForeground(new java.awt.Color(0, 0, 0));
        x1.setText("X1 Coordinate");
        x1.setOpaque(true);

        y2.setBackground(new java.awt.Color(255, 153, 0));
        y2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y2.setForeground(new java.awt.Color(0, 0, 0));
        y2.setText("y2 coordinate");
        y2.setOpaque(true);

        y1.setBackground(new java.awt.Color(255, 153, 0));
        y1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y1.setForeground(new java.awt.Color(0, 0, 0));
        y1.setText("y1 Coordinate");
        y1.setOpaque(true);

        ix1.setBackground(new java.awt.Color(0, 0, 0));
        ix1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix1.setForeground(new java.awt.Color(255, 153, 0));

        iy3.setBackground(new java.awt.Color(0, 0, 0));
        iy3.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy3.setForeground(new java.awt.Color(255, 153, 0));

        iy1.setBackground(new java.awt.Color(0, 0, 0));
        iy1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy1.setForeground(new java.awt.Color(255, 153, 0));

        drawTri.setBackground(new java.awt.Color(0, 0, 0));
        drawTri.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        drawTri.setForeground(new java.awt.Color(255, 153, 0));
        drawTri.setText("Draw Triangle");
        drawTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawTriActionPerformed(evt);
            }
        });

        y3.setBackground(new java.awt.Color(255, 153, 0));
        y3.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        y3.setForeground(new java.awt.Color(0, 0, 0));
        y3.setText("y3 coordinate");
        y3.setOpaque(true);

        x2.setBackground(new java.awt.Color(255, 153, 0));
        x2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x2.setForeground(new java.awt.Color(0, 0, 0));
        x2.setText("X2 coordinate");
        x2.setOpaque(true);

        x3.setBackground(new java.awt.Color(255, 153, 0));
        x3.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        x3.setForeground(new java.awt.Color(0, 0, 0));
        x3.setText("X3 coordinate");
        x3.setOpaque(true);

        ix3.setBackground(new java.awt.Color(0, 0, 0));
        ix3.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix3.setForeground(new java.awt.Color(255, 153, 0));

        iy2.setBackground(new java.awt.Color(0, 0, 0));
        iy2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        iy2.setForeground(new java.awt.Color(255, 153, 0));

        ix2.setBackground(new java.awt.Color(0, 0, 0));
        ix2.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        ix2.setForeground(new java.awt.Color(255, 153, 0));

        borderColor.setBackground(new java.awt.Color(0, 0, 0));
        borderColor.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        borderColor.setForeground(new java.awt.Color(255, 153, 0));
        borderColor.setText("Border color");
        borderColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorActionPerformed(evt);
            }
        });

        fillColor1.setBackground(new java.awt.Color(0, 0, 0));
        fillColor1.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        fillColor1.setForeground(new java.awt.Color(255, 153, 0));
        fillColor1.setText("Fill Color");
        fillColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(drawTri, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ix2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iy2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ix3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iy3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ix1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iy1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(borderColor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(fillColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ix1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(iy1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ix2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iy2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ix3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iy3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borderColor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(drawTri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(414, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void drawTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawTriActionPerformed
        // TODO add your handling code here:
        
        String strx1 = ix1.getText();
        String stry1 = iy1.getText();
        String strx2 = ix2.getText();
        String stry2 = iy2.getText();
        String strx3 = ix3.getText();
        String stry3 = iy3.getText();
//
//        
//        double a = Math.sqrt(Math.pow(x2 - x1 , 2) + Math.pow(y2 - y1 , 2));
//        double b = Math.sqrt(Math.pow(x3 - x2 , 2) + Math.pow(y3 - y2 , 2));
//        double c = Math.sqrt(Math.pow(x1 - x3 , 2) + Math.pow(y1 - y3 , 2));
//        
        if (strx1.equals("") || stry1.equals("") || strx2.equals("") || stry2.equals("") || strx3.equals("") || stry3.equals("")) {
            JOptionPane.showMessageDialog(null, "Some Fields are Empty !");
        }
        
        else if (!isNumeric(strx1) || !isNumeric(stry1) || !isNumeric(strx2) || !isNumeric(stry2) || !isNumeric(strx3) || !isNumeric(stry3) ) {
            JOptionPane.showMessageDialog(null, "Only Positive Numeric Values Are Allowed, Please Try Again!");
            if (!isNumeric(strx1)) {ix1.setText("");}
            if (!isNumeric(strx2)) {ix2.setText("");}
            if (!isNumeric(strx3)) {ix2.setText("");}
            if (!isNumeric(stry1)) {iy1.setText("");}
            if (!isNumeric(stry2)) {iy2.setText("");}
            if (!isNumeric(stry3)) {iy2.setText("");}

        }
        
//        else if (a + b <= c || a + c <= b || b + c <= a) {
//            JOptionPane.showMessageDialog(null, "Invalid Triangle Coordinates!");
//            ix1.setText("");
//            ix2.setText("");
//            iy1.setText("");
//            iy2.setText("");
//            ix3.setText("");
//            iy3.setText("");
//          }
        
        else {
            
            int x1 = Integer.parseInt(strx1);
            int y1 = Integer.parseInt(stry1);
            int x2 = Integer.parseInt(strx2);
            int y2 = Integer.parseInt(stry2);
            int x3 = Integer.parseInt(strx3);
            int y3 = Integer.parseInt(stry3);
            triangle = new Triangle(new Point(x1,y1), new Point(x2,y2), new Point(x3,y3));
            triangle.setColor(borderColor0);
            triangle.setFillColor(fillColor0);
            this.engine.addShape(triangle);
            this.triangle.draw(canvas.getGraphics());
            borderColor0 = Color.BLACK;
            fillColor0 = null;
            String rectangleName = "triangle" + this.numberOfTriangles;
            this.jComboBox.addItem(rectangleName);
            this.numberOfTriangles++;
            this.engine.refresh(canvas.getGraphics()); 
            this.setVisible(false);
//             Paint paint = (Paint) this.getParentNode();
//             paint.setVisible(true);
            ix1.setText("");
            ix2.setText("");
            iy1.setText("");
            iy2.setText("");
            ix3.setText("");
            iy3.setText("");
        }
            
    }//GEN-LAST:event_drawTriActionPerformed

    private void borderColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Enter Color :", Color.yellow);
        if(color != null) {
            this.borderColor0 = color;
        }
    }//GEN-LAST:event_borderColorActionPerformed

    private void fillColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColor1ActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Enter Color :", Color.yellow);
        if(color != null) {
            this.fillColor0 = color;
        }
    }//GEN-LAST:event_fillColor1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TriangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TriangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TriangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TriangleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TriangleWindow().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColor;
    private javax.swing.JButton drawTri;
    private javax.swing.JButton fillColor1;
    private javax.swing.JTextField ix1;
    private javax.swing.JTextField ix2;
    private javax.swing.JTextField ix3;
    private javax.swing.JTextField iy1;
    private javax.swing.JTextField iy2;
    private javax.swing.JTextField iy3;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    private javax.swing.JLabel y3;
    // End of variables declaration//GEN-END:variables
}
